require ("jvim.launch")
require ("jvim.options")
require ("jvim.keymaps")
require ("jvim.autocmds")
spec ("jvim.colorscheme")
spec ("jvim.devicons")
spec ("jvim.treesitter")
spec ("jvim.mason")
spec ("jvim.schemastore")
spec ("jvim.lspconfig")
spec ("jvim.cmp")
spec ("jvim.none-ls")
spec ("jvim.whichkey")
spec ("jvim.nvimtree")
spec ("jvim.telescope")
spec ("jvim.navic")
spec ("jvim.breadcrumbs")
spec ("jvim.comment")
spec ("jvim.lualine")
spec ("jvim.harpoon")
-- spec ("jvim.alpha")
spec ("jvim.startify")
spec ("jvim.hop")
spec ("jvim.gitsigns")
spec ("jvim.extras.neoscroll")
spec ("jvim.illuminate")
spec ("jvim.autopairs")
spec ("jvim.toggleterm")
-- spec ("jvim.neotest")
spec ("jvim.extras.oil")
spec ("jvim.extras.ufo")
-- spec ("jvim.extras.eyeliner")
spec ("jvim.extras.neotab")
-- spec ("jvim.extras.lab")
-- spec ("jvim.extras.copilot")
require ("jvim.lazy")
